apiVersion: batch/v1
kind: Job
metadata:
  name: numero-primo-job
  labels:
    app: numero-primo
spec:
  template:
    metadata:
      labels:
        app: numero-primo
    spec:
      containers:
      - name: numero-primo
        image: sergimp/numero-primo:latest
        args: ["5", "7", "11"]
      restartPolicy: Never
  backoffLimit: 4

