version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0  
    working_directory: ~/project/NumerosRomanosApp
    steps:
      - checkout
      - run:
          name: Verificar versión de Java
          command: java -version
      - run:
          name: mostrar estructura de archivos  
          command: tree -L 3
      - run:
          name: Compilar JavaVersionCheck.java
          command: javac src/main/java/JavaVersionCheck.java
      - run:
          name: Ejecutar JavaVersionCheck
          command: java -cp src/main/java JavaVersionCheck

