version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0 
    working_directory: ~/project/NumeroPrimoAPP  # Ajusta la carpeta raíz
    steps:
      - checkout
      - run:
          name: Verificar versión de Java
          command: java -version
      - run:
          name: mostrar contenido de la carpeta src/main/java
          command: ls -R 
      - run:
          name: Compilar Numero_Primo_Main
          command: javac src/main/java/Laboratorio/Numero_Primo_Main.java
      - run:
          name: Ejecutar Numero_Primo_Main
          command: java -cp src/main/java Laboratorio.Numero_Primo_Main
