version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0  # Imagen de Docker con Java
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Verificar versión de Java
          command: java -version
      - run:
          name: Compilar JavaVersionCheck.java
          command: javac JavaVersionCheck.java && java JavaVersionCheck
      - run:
          name: Construir con Maven
          command: mvn clean install
