version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0  # Usa la versión que necesites
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Verificar versión de Java
          command: java -version
      - run:
          name: Listar archivos disponibles
          command: ls -la
      - run:
          name: Compilar JavaVersionCheck.java
          command: javac src/main/java/JavaVersionCheck.java
      - run:
          name: Ejecutar JavaVersionCheck
          command: java -cp src/main/java JavaVersionCheck

