version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0 
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Verificar versión de Java
          command: java -version
      - run:
          name: mostrar contenido de la carpeta src/main/java
          command: ls -R NumeroPrimoAPP/src/main/java/Laboratorio/
      - run:
          name: Compilar todas las clases de NumeroPrimoAPP
          command: javac -d NumeroPrimoAPP/target/classes NumeroPrimoAPP/src/main/java/Laboratorio/*.java
      - run:
          name: Mostrar archivos compilados
          command: ls -R NumeroPrimoAPP/target/classes
      - run:
          name: Ejecutar Numero_Primo_Main con los valores 5, 10 y 15
          command: echo -e "5\n10\n15" | java -cp NumeroPrimoAPP/target/classes Laboratorio.Numero_Primo_Main


