version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0 
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Verificar versión de Java
          command: java -version
      - run:
          name: mostrar contenido de la carpeta src/main/java
          command: ls -R NumeroPrimoAPP/src/main/java/Laboratorio/
      - run:
          name: Compilar todas las clases de NumeroPrimoAPP
          command: javac NumeroPrimoAPP/src/main/java/Laboratorio/*.java
      - run:
          name: Ejecutar Numero_Primo_Main
          command: java -cp NumerpPrimoAPP/src/main/java Laboratorio.Numero_Primo_Main

